// @title           Matcha API
// @version         1.0
// @description     Dating API for Matcha
// @host            localhost:8080
// @BasePath        /
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"regexp"

	"matcha/api/internal/config"
	"matcha/api/internal/database"
	"matcha/api/internal/handlers"
	"matcha/api/internal/middleware"
	"matcha/api/internal/repository"
	"matcha/api/internal/search"
	"matcha/api/internal/services"
	"matcha/api/internal/storage"
	"matcha/api/internal/store"
	ws "matcha/api/internal/websocket"

	_ "matcha/api/docs" // generated by swag init

	"github.com/elastic/go-elasticsearch/v8"
	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @Summary	Health check
// @Router	/health [get]
func health(c *gin.Context) {
	c.String(http.StatusOK, "OK")
}

// @Summary	Ping
// @Router	/api/v1/ping [get]
func ping(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"status": "ok"})
}

func main() {
	ctx := context.Background()
	pool, err := database.NewPool(ctx, config.DatabaseURL())
	if err != nil {
		log.Fatalf("db: %v", err)
	}
	defer pool.Close()
	log.Println("DB connected")

	if err := database.RunMigrations(ctx, pool); err != nil {
		log.Fatalf("migration: %v", err)
	}

	userRepo := repository.NewUserRepository(pool)
	profileRepo := repository.NewProfileRepository(pool)
	likeRepo := repository.NewLikeRepository(pool)
	messageRepo := repository.NewMessageRepository(pool)
	notificationRepo := repository.NewNotificationRepository(pool)
	reportRepo := repository.NewReportRepository(pool)
	blockRepo := repository.NewBlockRepository(pool)
	presenceRepo := repository.NewPresenceRepository(pool)
	photoRepo := repository.NewPhotoRepository(pool)

	tokenStore, err := store.NewTokenStore(config.RedisURL())
	if err != nil {
		log.Fatalf("redis: %v", err)
	}
	defer tokenStore.Close()
	log.Println("Redis connected")

	authSvc := services.NewAuthService(userRepo, tokenStore)
	seedSvc := services.NewSeedService(userRepo, profileRepo, photoRepo)
	mailer := services.NewMailer(
		config.SMTPHost(),
		config.SMTPPort(),
		config.SMTPFrom(),
		config.SMTPCooldownSeconds(),
	)

	minioStore, err := storage.NewMinIO(
		config.MinIOEndpoint(),
		config.MinIOAccessKey(),
		config.MinIOSecretKey(),
		config.MinIOBucket(),
		config.MinIOPublicBaseURL(),
	)
	if err != nil {
		log.Fatalf("minio: %v", err)
	}
	if err := minioStore.EnsureBucket(ctx); err != nil {
		log.Fatalf("minio bucket: %v", err)
	}

	// Elasticsearch
	esCfg := elasticsearch.Config{Addresses: []string{config.ElasticsearchURL()}}
	searchClient, err := search.NewClient(esCfg)
	if err != nil {
		log.Fatalf("elasticsearch: %v", err)
	}
	if err := searchClient.EnsureIndex(ctx); err != nil {
		log.Fatalf("elasticsearch index: %v", err)
	}
	syncSvc := services.NewSyncService(userRepo, profileRepo, searchClient)
	if config.SeedUsersEnabled() {
		created, total, err := seedSvc.EnsureMinimumUsers(ctx, config.MinUsersCount())
		if err != nil {
			log.Fatalf("seed users: %v", err)
		}
		if created > 0 {
			log.Printf("Seeded profiles: +%d (total %d)", created, total)
		} else {
			log.Printf("Seed users skipped: already %d profiles", total)
		}
	}
	if err := syncSvc.ReindexAll(ctx); err != nil {
		log.Printf("elasticsearch reindex: %v (continuing)", err)
	}
	log.Println("Elasticsearch ready")

	discoveryRepo := repository.NewDiscoveryRepository(searchClient)

	authH := handlers.NewAuthHandler(
		authSvc,
		syncSvc,
		mailer,
		tokenStore,
		config.JWTSecret(),
		config.PublicAPIBaseURL(),
		config.FrontendBaseURL(),
	)
	wsHub := ws.NewHub()
	apiBaseURL := config.PublicAPIBaseURL()
	profileH := handlers.NewProfileHandler(profileRepo, photoRepo, syncSvc, minioStore, apiBaseURL)
	discoveryH := handlers.NewDiscoveryHandler(userRepo, profileRepo, photoRepo, likeRepo, blockRepo, notificationRepo, discoveryRepo, syncSvc, wsHub, minioStore, apiBaseURL)
	likesH := handlers.NewLikesHandler(likeRepo, userRepo, profileRepo, photoRepo, blockRepo, notificationRepo, mailer, syncSvc, wsHub, minioStore, apiBaseURL)
	chatH := handlers.NewChatHandler(messageRepo, likeRepo, userRepo, blockRepo, notificationRepo, mailer, wsHub)
	photoH := handlers.NewPhotoHandler(photoRepo, minioStore, apiBaseURL)
	notificationsH := handlers.NewNotificationsHandler(notificationRepo)
	reportsH := handlers.NewReportsHandler(reportRepo, userRepo)
	blocksH := handlers.NewBlocksHandler(blockRepo, userRepo)
	wsChatH := ws.NewChatHandler(wsHub, likeRepo, messageRepo, userRepo, blockRepo, notificationRepo, presenceRepo, mailer, config.JWTSecret())
	presenceH := handlers.NewPresenceHandler(presenceRepo, wsHub)

	r := gin.Default()
	// Allow localhost, 127.0.0.1, private IPs (192.168.x.x, 10.x.x.x), null, and CORS_ORIGIN
	allowedOrigin := config.CORSOrigin()
	localOriginRE := regexp.MustCompile(`^https?://(localhost|127\.0\.0\.1)(:\d+)?$`)
	privateIPRE := regexp.MustCompile(`^https?://(192\.168\.\d+\.\d+|10\.\d+\.\d+\.\d+)(:\d+)?$`)
	r.Use(cors.New(cors.Config{
		AllowMethods:     []string{"GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Content-Type", "Authorization"},
		AllowCredentials: true,
		AllowOriginFunc: func(origin string) bool {
			if origin == "" || origin == "null" {
				return true
			}
			if origin == allowedOrigin {
				return true
			}
			if localOriginRE.MatchString(origin) {
				return true
			}
			if privateIPRE.MatchString(origin) {
				return true
			}
			return false
		},
	}))

	r.GET("/health", health)
	r.GET("/api/v1/ping", ping)
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	authMw := middleware.Auth(config.JWTSecret())
	touchPresenceMw := middleware.TouchPresence(presenceRepo)

	api := r.Group("/api/v1")
	{
		api.GET("/photos/serve/:id", photoH.ServePhoto)
		api.POST("/auth/register", authH.Register)
		api.POST("/auth/login", authH.Login)
		api.GET("/auth/verify-email", authH.VerifyEmail)
		api.POST("/auth/forgot-password", authH.ForgotPassword)
		api.POST("/auth/reset-password", authH.ResetPassword)
		api.GET("/auth/me", authMw, touchPresenceMw, authH.Me)
		api.PATCH("/auth/me", authMw, touchPresenceMw, authH.UpdateMe)

		profile := api.Group("/profile")
		profile.Use(authMw, touchPresenceMw)
		{
			profile.GET("/me", profileH.GetMe)
			profile.PUT("/me", profileH.UpdateMe)
			profile.GET("/me/tags", profileH.GetMyTags)
			profile.PUT("/me/tags", profileH.UpdateMyTags)
			profile.GET("/tags/suggestions", profileH.TagSuggestions)
			profile.GET("/cities/suggestions", profileH.CitySuggestions)
			profile.GET("/me/views", profileH.GetViewedHistory)
		}

		users := api.Group("/users")
		users.Use(authMw, touchPresenceMw)
		{
			users.GET("", discoveryH.Search)
			users.GET("/:id", discoveryH.GetByID)
			users.GET("/:id/photos", photoH.ListByUser)
			users.POST("/:id/like", likesH.Like)
			users.POST("/:id/report", reportsH.ReportUser)
			users.POST("/:id/block", blocksH.BlockUser)
			users.DELETE("/:id/block", blocksH.UnblockUser)
			users.DELETE("/:id/like", likesH.Unlike)
			users.POST("/:id/messages", chatH.SendMessage)
			users.GET("/:id/messages", chatH.GetMessages)
			users.PATCH("/:id/messages/read", chatH.MarkRead)
		}

		photos := api.Group("/photos")
		photos.Use(authMw, touchPresenceMw)
		{
			photos.GET("/me", photoH.ListMe)
			photos.POST("", photoH.UploadMe)
			photos.DELETE("/:id", photoH.DeleteMe)
			photos.PATCH("/:id/primary", photoH.SetPrimaryMe)
		}

		api.GET("/likes/me", authMw, touchPresenceMw, likesH.GetLikedMe)
		api.GET("/likes", authMw, touchPresenceMw, likesH.GetLikedByMe)
		api.GET("/matches", authMw, touchPresenceMw, likesH.GetMatches)
		api.GET("/notifications", authMw, touchPresenceMw, notificationsH.List)
		api.PATCH("/notifications/read-all", authMw, touchPresenceMw, notificationsH.MarkAllRead)
		api.GET("/reports/me", authMw, touchPresenceMw, reportsH.ListMyReports)
		api.GET("/presence/:id", authMw, touchPresenceMw, presenceH.Get)
		api.GET("/ws/chat", wsChatH.Handle)
	}

	port := os.Getenv("API_PORT")
	if port == "" {
		port = "8080"
	}

	log.Printf("API :%s", port)
	r.Run(":" + port)
}
