// @title           Matcha API
// @version         1.0
// @description     Dating API for Matcha
// @host            localhost:8080
// @BasePath        /
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
package main

import (
	"context"
	"log"
	"net/http"
	"os"

	"matcha/api/internal/config"
	"matcha/api/internal/database"
	"matcha/api/internal/handlers"
	"matcha/api/internal/middleware"
	"matcha/api/internal/repository"
	"matcha/api/internal/search"
	"matcha/api/internal/services"

	"github.com/elastic/go-elasticsearch/v8"
	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	_ "matcha/api/docs" // generated by swag init
)

// @Summary	Health check
// @Router	/health [get]
func health(c *gin.Context) {
	c.String(http.StatusOK, "OK")
}

// @Summary	Ping
// @Router	/api/v1/ping [get]
func ping(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"status": "ok"})
}

func main() {
	ctx := context.Background()
	pool, err := database.NewPool(ctx, config.DatabaseURL())
	if err != nil {
		log.Fatalf("db: %v", err)
	}
	defer pool.Close()
	log.Println("DB connected")

	if err := database.RunMigrations(ctx, pool); err != nil {
		log.Fatalf("migration: %v", err)
	}

	userRepo := repository.NewUserRepository(pool)
	profileRepo := repository.NewProfileRepository(pool)
	likeRepo := repository.NewLikeRepository(pool)
	authSvc := services.NewAuthService(userRepo)

	// Elasticsearch
	esCfg := elasticsearch.Config{Addresses: []string{config.ElasticsearchURL()}}
	searchClient, err := search.NewClient(esCfg)
	if err != nil {
		log.Fatalf("elasticsearch: %v", err)
	}
	if err := searchClient.EnsureIndex(ctx); err != nil {
		log.Fatalf("elasticsearch index: %v", err)
	}
	syncSvc := services.NewSyncService(userRepo, profileRepo, searchClient)
	if err := syncSvc.ReindexAll(ctx); err != nil {
		log.Printf("elasticsearch reindex: %v (continuing)", err)
	}
	log.Println("Elasticsearch ready")

	discoveryRepo := repository.NewDiscoveryRepository(searchClient)

	authH := handlers.NewAuthHandler(authSvc, syncSvc, config.JWTSecret())
	profileH := handlers.NewProfileHandler(profileRepo, syncSvc)
	discoveryH := handlers.NewDiscoveryHandler(userRepo, profileRepo, discoveryRepo)
	likesH := handlers.NewLikesHandler(likeRepo, userRepo)

	r := gin.Default()
	r.Use(cors.New(cors.Config{
		AllowOrigins:     []string{config.CORSOrigin()},
		AllowMethods:     []string{"GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Content-Type", "Authorization"},
		AllowCredentials: true,
	}))

	r.GET("/health", health)
	r.GET("/api/v1/ping", ping)
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	api := r.Group("/api/v1")
	{
		api.POST("/auth/register", authH.Register)
		api.POST("/auth/login", authH.Login)
		api.GET("/auth/me", middleware.Auth(config.JWTSecret()), authH.Me)

		profile := api.Group("/profile")
		profile.Use(middleware.Auth(config.JWTSecret()))
		{
			profile.GET("/me", profileH.GetMe)
			profile.PUT("/me", profileH.UpdateMe)
		}

		users := api.Group("/users")
		users.Use(middleware.Auth(config.JWTSecret()))
		{
			users.GET("", discoveryH.Search)
			users.GET("/:id", discoveryH.GetByID)
			users.POST("/:id/like", likesH.Like)
			users.DELETE("/:id/like", likesH.Unlike)
		}

		api.GET("/likes/me", middleware.Auth(config.JWTSecret()), likesH.GetLikedMe)
		api.GET("/likes", middleware.Auth(config.JWTSecret()), likesH.GetLikedByMe)
		api.GET("/matches", middleware.Auth(config.JWTSecret()), likesH.GetMatches)
	}

	port := os.Getenv("API_PORT")
	if port == "" {
		port = "8080"
	}

	log.Printf("API :%s", port)
	r.Run(":" + port)
}
