# Dev image with hot reload (air)
FROM golang:1.23-alpine

WORKDIR /app
ENV GOTOOLCHAIN=auto

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .
# air will rebuild on file changes

EXPOSE 8080
CMD ["air", "-c", ".air.toml"]
